[package]
name = "bsub"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bcap = { path = "../bcap" }
clap = { version = "4.5.13", features = ["derive"] }
csv = "1.3.0"
mac6 = "1.0.0"
serde = { version = "1.0.204", features = ["derive"] }
