//! Contains country information.

use strum::{AsRefStr, Display, EnumString, IntoStaticStr};

// https://github.com/annexare/Countries/blob/main/dist/countries.min.json

/// Representation of a country
#[derive(
    Debug, Clone, Copy, Display, EnumString, AsRefStr, IntoStaticStr, PartialEq, Eq, PartialOrd, Ord,
)]
pub enum Country {
    AD,
    AE,
    AF,
    AG,
    AI,
    AL,
    AM,
    AO,
    AQ,
    AR,
    AS,
    AT,
    AU,
    AW,
    AX,
    AZ,
    BA,
    BB,
    BD,
    BE,
    BF,
    BG,
    BH,
    BI,
    BJ,
    BL,
    BM,
    BN,
    BO,
    BQ,
    BR,
    BS,
    BT,
    BV,
    BW,
    BY,
    BZ,
    CA,
    CC,
    CD,
    CF,
    CG,
    CH,
    CI,
    CK,
    CL,
    CM,
    CN,
    CO,
    CR,
    CU,
    CV,
    CW,
    CX,
    CY,
    CZ,
    DE,
    DJ,
    DK,
    DM,
    DO,
    DZ,
    EC,
    EE,
    EG,
    EH,
    ER,
    ES,
    ET,
    FI,
    FJ,
    FK,
    FM,
    FO,
    FR,
    GA,
    GB,
    GD,
    GE,
    GF,
    GG,
    GH,
    GI,
    GL,
    GM,
    GN,
    GP,
    GQ,
    GR,
    GS,
    GT,
    GU,
    GW,
    GY,
    HK,
    HM,
    HN,
    HR,
    HT,
    HU,
    ID,
    IE,
    IL,
    IM,
    IN,
    IO,
    IQ,
    IR,
    IS,
    IT,
    JE,
    JM,
    JO,
    JP,
    KE,
    KG,
    KH,
    KI,
    KM,
    KN,
    KP,
    KR,
    KW,
    KY,
    KZ,
    LA,
    LB,
    LC,
    LI,
    LK,
    LR,
    LS,
    LT,
    LU,
    LV,
    LY,
    MA,
    MC,
    MD,
    ME,
    MF,
    MG,
    MH,
    MK,
    ML,
    MM,
    MN,
    MO,
    MP,
    MQ,
    MR,
    MS,
    MT,
    MU,
    MV,
    MW,
    MX,
    MY,
    MZ,
    NA,
    NC,
    NE,
    NF,
    NG,
    NI,
    NL,
    NO,
    NP,
    NR,
    NU,
    NZ,
    OM,
    PA,
    PE,
    PF,
    PG,
    PH,
    PK,
    PL,
    PM,
    PN,
    PR,
    PS,
    PT,
    PW,
    PY,
    QA,
    RE,
    RO,
    RS,
    RU,
    RW,
    SA,
    SB,
    SC,
    SD,
    SE,
    SG,
    SH,
    SI,
    SJ,
    SK,
    SL,
    SM,
    SN,
    SO,
    SR,
    SS,
    ST,
    SV,
    SX,
    SY,
    SZ,
    TC,
    TD,
    TF,
    TG,
    TH,
    TJ,
    TK,
    TL,
    TM,
    TN,
    TO,
    TR,
    TT,
    TV,
    TW,
    TZ,
    UA,
    UG,
    UM,
    US,
    UY,
    UZ,
    VA,
    VC,
    VE,
    VG,
    VI,
    VN,
    VU,
    WF,
    WS,
    XK,
    YE,
    YT,
    ZA,
    ZM,
    ZW,
}

impl Country {
    /// Get the name of the country as a str slice.
    pub fn name(&self) -> &'static str {
        match self {
            Self::AD => "Andorra",
            Self::AE => "دولة الإمارات العربية المتحدة",
            Self::AF => "افغانستان",
            Self::AG => "Antigua and Barbuda",
            Self::AI => "Anguilla",
            Self::AL => "Shqipëria",
            Self::AM => "Հայաստան",
            Self::AO => "Angola",
            Self::AQ => "Antarctica",
            Self::AR => "Argentina",
            Self::AS => "American Samoa",
            Self::AT => "Österreich",
            Self::AU => "Australia",
            Self::AW => "Aruba",
            Self::AX => "Åland",
            Self::AZ => "Azərbaycan",
            Self::BA => "Bosna i Hercegovina",
            Self::BB => "Barbados",
            Self::BD => "Bangladesh",
            Self::BE => "België",
            Self::BF => "Burkina Faso",
            Self::BG => "България",
            Self::BH => "‏البحرين",
            Self::BI => "Burundi",
            Self::BJ => "Bénin",
            Self::BL => "Saint-Barthélemy",
            Self::BM => "Bermuda",
            Self::BN => "Negara Brunei Darussalam",
            Self::BO => "Bolivia",
            Self::BQ => "Bonaire",
            Self::BR => "Brasil",
            Self::BS => "Bahamas",
            Self::BT => "ʼbrug-yul",
            Self::BV => "Bouvetøya",
            Self::BW => "Botswana",
            Self::BY => "Белару́сь",
            Self::BZ => "Belize",
            Self::CA => "Canada",
            Self::CC => "Cocos (Keeling) Islands",
            Self::CD => "République démocratique du Congo",
            Self::CF => "Ködörösêse tî Bêafrîka",
            Self::CG => "République du Congo",
            Self::CH => "Schweiz",
            Self::CI => "Côte d'Ivoire",
            Self::CK => "Cook Islands",
            Self::CL => "Chile",
            Self::CM => "Cameroon",
            Self::CN => "中国",
            Self::CO => "Colombia",
            Self::CR => "Costa Rica",
            Self::CU => "Cuba",
            Self::CV => "Cabo Verde",
            Self::CW => "Curaçao",
            Self::CX => "Christmas Island",
            Self::CY => "Κύπρος",
            Self::CZ => "Česká republika",
            Self::DE => "Deutschland",
            Self::DJ => "Djibouti",
            Self::DK => "Danmark",
            Self::DM => "Dominica",
            Self::DO => "República Dominicana",
            Self::DZ => "الجزائر",
            Self::EC => "Ecuador",
            Self::EE => "Eesti",
            Self::EG => "مصر‎",
            Self::EH => "الصحراء الغربية",
            Self::ER => "ኤርትራ",
            Self::ES => "España",
            Self::ET => "ኢትዮጵያ",
            Self::FI => "Suomi",
            Self::FJ => "Fiji",
            Self::FK => "Falkland Islands",
            Self::FM => "Micronesia",
            Self::FO => "Føroyar",
            Self::FR => "France",
            Self::GA => "Gabon",
            Self::GB => "United Kingdom",
            Self::GD => "Grenada",
            Self::GE => "საქართველო",
            Self::GF => "Guyane française",
            Self::GG => "Guernsey",
            Self::GH => "Ghana",
            Self::GI => "Gibraltar",
            Self::GL => "Kalaallit Nunaat",
            Self::GM => "Gambia",
            Self::GN => "Guinée",
            Self::GP => "Guadeloupe",
            Self::GQ => "Guinea Ecuatorial",
            Self::GR => "Ελλάδα",
            Self::GS => "South Georgia",
            Self::GT => "Guatemala",
            Self::GU => "Guam",
            Self::GW => "Guiné-Bissau",
            Self::GY => "Guyana",
            Self::HK => "香港",
            Self::HM => "Heard Island and McDonald Islands",
            Self::HN => "Honduras",
            Self::HR => "Hrvatska",
            Self::HT => "Haïti",
            Self::HU => "Magyarország",
            Self::ID => "Indonesia",
            Self::IE => "Éire",
            Self::IL => "יִשְׂרָאֵל",
            Self::IM => "Isle of Man",
            Self::IN => "भारत",
            Self::IO => "British Indian Ocean Territory",
            Self::IQ => "العراق",
            Self::IR => "ایران",
            Self::IS => "Ísland",
            Self::IT => "Italia",
            Self::JE => "Jersey",
            Self::JM => "Jamaica",
            Self::JO => "الأردن",
            Self::JP => "日本",
            Self::KE => "Kenya",
            Self::KG => "Кыргызстан",
            Self::KH => "Kâmpŭchéa",
            Self::KI => "Kiribati",
            Self::KM => "Komori",
            Self::KN => "Saint Kitts and Nevis",
            Self::KP => "북한",
            Self::KR => "대한민국",
            Self::KW => "الكويت",
            Self::KY => "Cayman Islands",
            Self::KZ => "Қазақстан",
            Self::LA => "ສປປລາວ",
            Self::LB => "لبنان",
            Self::LC => "Saint Lucia",
            Self::LI => "Liechtenstein",
            Self::LK => "śrī laṃkāva",
            Self::LR => "Liberia",
            Self::LS => "Lesotho",
            Self::LT => "Lietuva",
            Self::LU => "Luxembourg",
            Self::LV => "Latvija",
            Self::LY => "‏ليبيا",
            Self::MA => "المغرب",
            Self::MC => "Monaco",
            Self::MD => "Moldova",
            Self::ME => "Црна Гора",
            Self::MF => "Saint-Martin",
            Self::MG => "Madagasikara",
            Self::MH => "M̧ajeļ",
            Self::MK => "Северна Македонија",
            Self::ML => "Mali",
            Self::MM => "မြန်မာ",
            Self::MN => "Монгол улс",
            Self::MO => "澳門",
            Self::MP => "Northern Mariana Islands",
            Self::MQ => "Martinique",
            Self::MR => "موريتانيا",
            Self::MS => "Montserrat",
            Self::MT => "Malta",
            Self::MU => "Maurice",
            Self::MV => "Maldives",
            Self::MW => "Malawi",
            Self::MX => "México",
            Self::MY => "Malaysia",
            Self::MZ => "Moçambique",
            Self::NA => "Namibia",
            Self::NC => "Nouvelle-Calédonie",
            Self::NE => "Niger",
            Self::NF => "Norfolk Island",
            Self::NG => "Nigeria",
            Self::NI => "Nicaragua",
            Self::NL => "Nederland",
            Self::NO => "Norge",
            Self::NP => "नेपाल",
            Self::NR => "Nauru",
            Self::NU => "Niuē",
            Self::NZ => "New Zealand",
            Self::OM => "عمان",
            Self::PA => "Panamá",
            Self::PE => "Perú",
            Self::PF => "Polynésie française",
            Self::PG => "Papua Niugini",
            Self::PH => "Pilipinas",
            Self::PK => "Pakistan",
            Self::PL => "Polska",
            Self::PM => "Saint-Pierre-et-Miquelon",
            Self::PN => "Pitcairn Islands",
            Self::PR => "Puerto Rico",
            Self::PS => "فلسطين",
            Self::PT => "Portugal",
            Self::PW => "Palau",
            Self::PY => "Paraguay",
            Self::QA => "قطر",
            Self::RE => "La Réunion",
            Self::RO => "România",
            Self::RS => "Србија",
            Self::RU => "Россия",
            Self::RW => "Rwanda",
            Self::SA => "العربية السعودية",
            Self::SB => "Solomon Islands",
            Self::SC => "Seychelles",
            Self::SD => "السودان",
            Self::SE => "Sverige",
            Self::SG => "Singapore",
            Self::SH => "Saint Helena",
            Self::SI => "Slovenija",
            Self::SJ => "Svalbard og Jan Mayen",
            Self::SK => "Slovensko",
            Self::SL => "Sierra Leone",
            Self::SM => "San Marino",
            Self::SN => "Sénégal",
            Self::SO => "Soomaaliya",
            Self::SR => "Suriname",
            Self::SS => "South Sudan",
            Self::ST => "São Tomé e Príncipe",
            Self::SV => "El Salvador",
            Self::SX => "Sint Maarten",
            Self::SY => "سوريا",
            Self::SZ => "Eswatini",
            Self::TC => "Turks and Caicos Islands",
            Self::TD => "Tchad",
            Self::TF => "Territoire des Terres australes et antarctiques fr",
            Self::TG => "Togo",
            Self::TH => "ประเทศไทย",
            Self::TJ => "Тоҷикистон",
            Self::TK => "Tokelau",
            Self::TL => "Timor-Leste",
            Self::TM => "Türkmenistan",
            Self::TN => "تونس",
            Self::TO => "Tonga",
            Self::TR => "Türkiye",
            Self::TT => "Trinidad and Tobago",
            Self::TV => "Tuvalu",
            Self::TW => "臺灣",
            Self::TZ => "Tanzania",
            Self::UA => "Україна",
            Self::UG => "Uganda",
            Self::UM => "United States Minor Outlying Islands",
            Self::US => "United States",
            Self::UY => "Uruguay",
            Self::UZ => "O'zbekiston",
            Self::VA => "Vaticano",
            Self::VC => "Saint Vincent and the Grenadines",
            Self::VE => "Venezuela",
            Self::VG => "British Virgin Islands",
            Self::VI => "United States Virgin Islands",
            Self::VN => "Việt Nam",
            Self::VU => "Vanuatu",
            Self::WF => "Wallis et Futuna",
            Self::WS => "Samoa",
            Self::XK => "Republika e Kosovës",
            Self::YE => "اليَمَن",
            Self::YT => "Mayotte",
            Self::ZA => "South Africa",
            Self::ZM => "Zambia",
            Self::ZW => "Zimbabwe",
        }
    }
}
